seed-atl-1: ENC[AES256_GCM,data:EOr/Je6O+ZKN8P0FzaBbWr1NTZaYKN31eNl5BkQ3P1p7DLhwwQfTAbsl8dw=,iv:ggKi7u92GsEY6L9SL7Fy2h/b8nMAcXGd6c7oKBUacbM=,tag:RvqwB0AarxwY0Uoi3xW3wg==,type:str]
seed-atl-2: ENC[AES256_GCM,data:MTXOYI0NgIHLSZyhnTtVDgvmrUra56lVwFu1FDXSwacPYjn51mN+3tGkPUI=,iv:BE3wm3Fx/JC3nlFVTkRAVnRgA0yAQCPVCyHTgwQyf4c=,tag:7mtjAEAQTUjtDjXhG5T4Fg==,type:str]
seed-atl-3: ENC[AES256_GCM,data:Ne9b/GuwRl8NJRSC/d1C0GHsvaVXEFXIAAfeXqnyK4REnyfNxkWHttSfN9k=,iv:8zRmKnTd3w1nEwDPzsVMiMTl6SqywJucMcl1YBL3EAg=,tag:RT2LvyFAgTqzipX43RYyeg==,type:str]
sops:
    age:
        - recipient: age1ujjm7feyd3p2e0qtfa6zr2rzf593yd2z0xjn0ytvd8jcje68nansxy4zuu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHY1pqODdpcU1yNlZ2LytO
            WllYRm1iN0ozQTJZNEptQUViYzNadldoQm5JCnlxTnR5UmJBZmtaM2g0R3VIaTJR
            VkdhUDVnRFZRL0R0RjNVSWhRVTA2SGsKLS0tIENwUCtnNjROQU5rdmNXRHh4ekVu
            QXBXZHlGTE40UnIvSS9TRmw0NWhBVDQKaILcZGog7cAkUHhgEoGgreuV2lAjrCiK
            bHBPF4YU1jO6pU/i5yG9M5jbMZ0SbN1czr52jHQlV/Kdji5GXuNe+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T20:58:10Z"
    mac: ENC[AES256_GCM,data:8wCjwCdYFkew17ai4WgHeD0OkJW2H9noPDXzUzjEqunDx6bQGltmA2JrAxL8iI0RQ72v4E9gR2bJsgWn/MCKwaOgkJTnOBnj6EwdCp2rrKADJhCiYShkmvPu8mKvvZGpULga544odzPzLDCay2oQhD11EKvLCByDfxAzyLxdMgo=,iv:P72P306AqHkIIec2+xN16petzwrQ2oA3xn7GcCDPo9Y=,tag:7Wnwa/h/jQ//rQjQ2I0A1w==,type:str]
    pgp:
        - created_at: "2026-03-10T20:58:10Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DWp+nDyPN4uwSAQdAF0Itm+KGyqAiMq3NKEyFgV881hQcns3NN4gEqRPjoTgw
            WD0022VMvflexzspMiFjguBkmmid3xR1/fFBhaMHOcUOVrqmSP0lQ4ex3rxU4P1I
            0l4B35NDXk6t0CAKka0V6X6s1o/Iz0UQukTh7axCYxBOhSmfkS50Mvtfranoo5N5
            Ovvg9Zro9Mt85lMyp927eJN41aOyDxjXItxMALwaWNw4B/I/9gOphT6a0Ri+B76B
            =8xfI
            -----END PGP MESSAGE-----
          fp: 2EE325D71601671696EBF687E45953D34C8829ED
    unencrypted_suffix: _unencrypted
    version: 3.12.1
