placeholder: ENC[AES256_GCM,data:Cof4Yw==,iv:qpponXBmkbb/MlIpA8DNzB/TzkGuGuEqldqf8OFXS/k=,tag:Kh+jmEClxut886xhDWAJWg==,type:bool]
sops:
    age:
        - recipient: age1kazl566j80pl3eshzqv9c0wyq843g8ep7vt27su03e4jg6eg64gqv6qnwl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZUDBPSHhPT2VJanRyQ0Vi
            bEMwTUxhY2FiZGxrWUVBQ0JqNlJMUWdzRm1FClFBSERFaUFtUkEra0RGYUVnUVNG
            Q3Mxd25QMElXZmpFTUF6T2xrMTRQdmsKLS0tIHhiV213WDczaVJBUTA5WHEvUUFE
            K09vVE1kUHJsb3lScGlNUytRemNXT2MKv6fhCyU77a4WJShkodcZtDjNVrCc0Jmd
            qI4UH6KzPJNhSg2ScS2jdnhbKYCqlFb45LHlgRGuC3k9Rm1wl/ITJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-14T23:50:12Z"
    mac: ENC[AES256_GCM,data:TL8R84l0iXPRP3OzjO0jsqdxTTSR+/7R1G7xD9ve8Yio8FzhpViYDhsCJtXJDLyb0YUanG3G4rdz6L1gWIAa8kUBvYaSinK46kegsQRsDvgM0zu3bcnDsDUy3ttXKfeZJ/NhysmLI4hZOcQctlCuEGpL5U06ah0Sivo3226Xdfk=,iv:+8HKsCQgF35jxqT5komaBkpVVE5I9uMjl3ZRCJwobuI=,tag:2Otxstcsm8L30gNzXkKVfw==,type:str]
    pgp:
        - created_at: "2026-03-14T23:50:12Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DWp+nDyPN4uwSAQdAu2/6sOpYBNRtg6H8BLxLuC5b1DwTZEzHSDJqFWx2lm4w
            Hq5wJggH3gEmCsosGLEM83A/EwrPGI2UYzmI2VjsFrgYED1nYwnhD1ruSNKEyZFm
            0lwBPHLQCpuYBxRleHziicT9ujJ3aIiB7f3rQwQIUxSCk1wedyHVZ+tPyPub6dHq
            XQo1Erb6JycxJ8DaZNZrixYUlD5kP8ONU2PDXX6Ut5DBokhuowSibz2RdEBQWg==
            =fO7V
            -----END PGP MESSAGE-----
          fp: 2EE325D71601671696EBF687E45953D34C8829ED
    unencrypted_suffix: _unencrypted
    version: 3.11.0
