seed:
    k3s-token: ENC[AES256_GCM,data:L1HvZzty+7wIddXRJ/UpQjuWuk4O7z1herp2dEj7YVXiM7WRfX/QZhCCVSfQVcd8POqsK4MJ9QzBnycc9ECrIw==,iv:EOOwyQ1Z07GvQix5KELizIj1v4QGsR9+Lv0taFZJXRQ=,tag:WIsdLR21bgQoBft9UP/yzQ==,type:str]
sops:
    age:
        - recipient: age1ggj5uuyt5x0vrt4fmcu8lnt0f3qzqkxjm8qpqrplckvpz2s2ugdquuzn78
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRTkN6ampTQzc5R3l1U010
            THRRcXZLVmZ5enJOS3FPNXAwS0VMbmxyNDNnCmw3d0E0UGVVNTd4STJyb3pYOUNV
            VmdhTGx3TUZkNXplcmR4ZHp3MnVNQzAKLS0tIHl5UjExSzkrbWxDZldoVFpnQ3Zh
            M1c2cFJrb21qT1RLWWJjd2JGejlHZkkKYN8jYaVW9Hmoeduh/7Yj9125rUt4Z6pu
            qeQtUoeKg/Q6JfGD5vM+6bd6RBbniL8T/bn+6ZmxEzYyHl9mhPGzBg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ujjm7feyd3p2e0qtfa6zr2rzf593yd2z0xjn0ytvd8jcje68nansxy4zuu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEZll5NnE4bDRMNmxDelFt
            alNZbjVQYkRhK2d1bjRIbDVpVS9vaDdPdHpNCmNQOUF3cGRpMG5qdzlUdXA2Q3Rt
            VnNvQzdmOHd1bkhJRnRhNHY2eXljOHcKLS0tIEtPWWplUmZqSUExVTdROTlVWWVN
            bjhETFBxKzRlaHdwS0xiMXFKbzRrQncKYi2Av88WI4VEH6gyCdMc/m8D4jRPyAXY
            AmXeuc9TXRnP8ak2r4jrTMkVaRF0/Lt8ShHvVVZRrxpLULbrQS3+hg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T01:19:50Z"
    mac: ENC[AES256_GCM,data:r2YzSEqF+hmB7UBNijBQPmd6qyiOfnbiHJP8GQBO3gnkq4H1MB9N20eBMe0tvZ8M+DbBPGlDv29ewm2vu3uGqKfwjz6d0asMerUq7tKEYZJwqmRa+e6/8p1Y0kabnQ6AhYnspclYAUx0j0JrccrpYdeVA+AbKnXjlXMZeepeAM8=,iv:hP61wGTpj29Tu37j4y7JoRIy12c3PVFyPYGn9JyHq0A=,tag:Fre9DCOMpu2AcJeq9/9HbA==,type:str]
    pgp:
        - created_at: "2026-03-15T01:19:50Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DWp+nDyPN4uwSAQdAXPMZJqw/CfX785NghV+MwWLa92B0s6911KyM4qSy7i4w
            Je3YbsVqyScPR+crsbV2vCbFH7fMiDJf9A+xYngICi1bQ3vht6zOsyR/Nbc3ZSNo
            0l4BFJpoUWTndh6X0xKzp1qQi3V4krhX3CZS1JvNeTK6nuqd6wGc9qjEEA+fB+JL
            /jL9iRy9UVWNRxHM1iXSzHujKpZ5GFBGu/u6VtPgRLedx9r+3RGo13X64CoBIuPp
            =0oXM
            -----END PGP MESSAGE-----
          fp: 2EE325D71601671696EBF687E45953D34C8829ED
    unencrypted_suffix: _unencrypted
    version: 3.11.0
