seed:
    k3s-token: ENC[AES256_GCM,data:DXLxSY9GNK4PvOZ2Pl3JoxJDI26T4HOe+J3azuz/AIhur2gAXS5EEEX8r1AyhinhNtHdMR4blPM8qKKvzHIX5vUObdqUsVawOm8OeYqjl7QCHK5NwPLhXtzIUt1T5/6vHYXQ5Cs7ZN2f56Ni8kbLU8c178bauU73aL6MzKpqvKN6/n1XolqqoHR0NUo=,iv:2vFi5ktJtHozP7H57V2vuRv3oJVFCLCdg7YVGwgCj5s=,tag:gJkYVFPYeL8zizF8xR0Wiw==,type:str]
sops:
    age:
        - recipient: age1x6fmwskwxvacf9nnsafexvpgfdl9ugj9xf9fvpvfng3rkukc3yxskddr3p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJaVNmeitBSzRtQWVVMWhl
            cUxRZVhRU2FXcXlBNEV2WmVJVUgyZFhWQXpRCnNLV3RhNDM0QmJ6b3lUWVdXeGNF
            Z1kyVkxibTdYREdwWEJRMWpBUjhuSUkKLS0tIEhSb3dWcGNxeUJ6R3JoM05rTytL
            R25RbzdsZG5OdTM1V0FrYnFtSy9NOW8KxLFk3JWIb4UYsSduq7tMHqOVcVQIZHMv
            XJ3s1GypNW2995C7QKUyA9p9amukgrKxWUeJvlibNMfQJEieEC2A/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-13T05:23:13Z"
    mac: ENC[AES256_GCM,data:XCHI6w9h7trLGBQHS+gG37Nzt13MNzd4ddgCcglbivVrLAgSIVcu4uLcaxtpZEdTW3JBPsVOZjDs0Kel4SRsn7GiLIcD1rQHNnKl9XKS48qIPfZaPepLKgJoUJ/bwnmvjs4VvXRaJP7rLWsUgqaeV7LXl6qfFAMjtBpMDdU0m9s=,iv:P+3olwKmAYegQ8fiXzBdUAnR8RVBXazmiAQg/GmS54w=,tag:notGymy/C9SCwbRh0f1AOQ==,type:str]
    pgp:
        - created_at: "2026-03-13T05:23:13Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DWp+nDyPN4uwSAQdAH+CIfJLs5dIpGb09DyrNfeJWxtutpRkFdWBDkT4M904w
            r8dXNVjQPTc1DclTBVJ1OiWboz/pEbffO25OMKJVNIL8sBlmCkyuzZsc83/zZs/i
            0l4BBSll1DIDPrhWTirP1yNlKJWUCHqojZ+kpvVy3mpoU1aXRNkUWOxrpWbbHuZ8
            V3VxAzkxtbmQoxNqXwPLubrga+ldVEgO2oKsFcdfB2Yy7g8JSRQyZvobGn9NS81J
            =7lPI
            -----END PGP MESSAGE-----
          fp: 2EE325D71601671696EBF687E45953D34C8829ED
    unencrypted_suffix: _unencrypted
    version: 3.11.0
