seed:
    k3s-token: ENC[AES256_GCM,data:csg2C73HSAPyecRIPKvZF6mA6QI3l65OXtDJslyoynFd4oES5XCg1CkaeT2BchgJ40UHe4uOMEQE1jBTEsy8BcLmQxg+VspJjrVZtQLxdXS6jJ+JmNvigQU+CYntw3nkNnARYHXk+d8Pp/w9UI7qeGLYRiXPzNt4q5CtZpikHYeMZ3WiO31pIS3izz4=,iv:cBDErFp15aW+tBig412Mlzhijxfe7gOpFbaRp/jU40k=,tag:krRovIc8fH85mK/TDM7gow==,type:str]
sops:
    age:
        - recipient: age19xq48wjmej07g6sl8kg86a64jsxe5gc47y2f6ghefjxeqhhcad7q4sm0vx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0K1JmMHNDUWpzeHJRQ0hY
            ZlJvVE50MmwyR1MwZTFwT0IyVUE0eDREUW5BClBsZmo0V0drdnVwNG5FSkRkMS9U
            UTZ3OUgySDBaL0FCK0U0Q1VMc2s1L1EKLS0tIG5oSkNuenpuc25iTndKdXFaeXQr
            cXUwM29vUyttQnJrTEFLNmFVTEFYbEkK+ix42/jwRAgSHARKK9odlPHz+Th6yZZH
            VsugOTB+hvnfQU2l2fIkoCHvC0rm9H6J3CsD9ZkxECh+49WRWIzGkQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T20:58:08Z"
    mac: ENC[AES256_GCM,data:NLp0HKB3gIXWs+mZdi8XMyqCDqwGSecAXie32cPBK+kjN0oAlajO2a/RyfayD+hJV/Mq/nDTJiokh5eMbMW373AfKEi7zIweenJMBlElYuY+KNiAQCGmHrlvmDL5nTHaV4MCA0FWKYYYeOCmORv+dcAk1TsgUORKpi2/mWUdNfE=,iv:+J7Wr7BoKwKCg48lw96dmPkVg9CArWsWX4O7C6bzQc0=,tag:lMKRGDfMXfEe9vuxiS3rzA==,type:str]
    pgp:
        - created_at: "2026-03-10T20:58:08Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DWp+nDyPN4uwSAQdA5yP23TjMdeR/2FGdbJdAWvt6pzgt+bCG6oAEF05C7hQw
            0p1EFM8JVRBLIjnOZWIPqtrp+hWyaitXRUC4BZtaFc0yTv+sEb2kvd24dURTK4QZ
            0l4BnsOc7jK6OsFN1bSkDwI3zX6BxT9cbhloajG38At83NZHbMWl/a/wmHV88fkr
            e7PFKb7eWfnxFeKZ4TBfiICWjzHLtdZIl6gxhuNCtu5LJznQghPQgmS8Kwtv8Lgy
            =oHGJ
            -----END PGP MESSAGE-----
          fp: 2EE325D71601671696EBF687E45953D34C8829ED
    unencrypted_suffix: _unencrypted
    version: 3.12.1
