seed:
    k3s-token: ENC[AES256_GCM,data:GKUOO2qAAgEeLfUp2tgSnYO0/8dbLEml8A2CgQoi6I+3WuvKigNT8l1NSmlw+Mf5KiGAMfJ/EARBTRaL+6yfog==,iv:q2yKllENhXBLwFDlReWdlHKnPQhflwxM5IYsMK2COhI=,tag:cf6Fw0rRZAkTFIWL0vKELw==,type:str]
sops:
    age:
        - recipient: age1neey2tjnrka26dndtwp400y5auud86v92f09srdr3xun80exv5jqcnlq6t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2WFhqZ0NCczNibzREVnZ2
            cWxnaGhvQXhpMVlsZDdnZE9jQU9SemhrdEQ0ClhuS28zTFNieWJTS3lhQUZBNFZn
            M0czWHgzOEFvRHpad25JRnpMTnZ2a00KLS0tIGowZFAwZHNEYlZUQmIvYUM3SkN5
            a1hhU01qNG5YcVl3ZGZvdUwrU3Zsa1EKz+qS4vfKpejTutK8wZzgEH2lINDNeUAI
            RteXL9o4EPFyy71CxWSs4I2uZqgv4gyraWzI8I2gk62Kjcfh9QPbDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-13T02:12:49Z"
    mac: ENC[AES256_GCM,data:96/CFEhQzRPnqh/GPMBvxZjJmjk8ZKwfN4GEiWiDSFdEVmH+6QC6cL6yhHWDXG2Kyhrmsis/z7TYJ1VOG1frZ4TOraNEepaNKEZpF07XrDfXGboSu12GEqnVgno03xG/SCv5+UPBZCuld8F/LkGgTT6ye62AnOD6K42QwUsMOXI=,iv:VacT/icQt8MypDIamTrXNQMoZuEJ2C5S1azJ+yeHo1Y=,tag:USe0PmXbn3T8sorjXOpcZQ==,type:str]
    pgp:
        - created_at: "2026-03-13T02:12:49Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DWp+nDyPN4uwSAQdAcHLUdV1vDOeRnSEP/bzwu1PPAV9j67d0iSzu8s4k5yYw
            5StPNAwsMmf52MIMuZu/Ta9RK4329iUf5BGTAPk1AfTIWtksanzGByWcDoMxlAjP
            0lwB6tUE0l2ID4dxiZVR08+TXZB/DgSZUiX9kFB/+bV0Z0sShUBnAQkFSCxsuQo/
            t7715c4eols3Fls/DYceoFzaxdSWY3MFxq5Cf/CNVKCFNh1VAc6ZxjGs6OMyzw==
            =pNgl
            -----END PGP MESSAGE-----
          fp: 2EE325D71601671696EBF687E45953D34C8829ED
    unencrypted_suffix: _unencrypted
    version: 3.11.0
