vultr-api-key: ENC[AES256_GCM,data:a51UHbOfb6gN6K/P0txLAotUh/InDdX67mTiUc3IElQhxemA,iv:Vex8b1sWkL+ioe5Yy0JFtiw2QE/faQEuiu5GPCUr4Sw=,tag:pljMApD7of8H33VriBlKFA==,type:str]
sops:
    age:
        - recipient: age1ae83xwy93c4u9nrzu8gtdyr9ks9c3zu44p7dmc78penpenaysgnqq5xqgx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDaDI2U1JJM1JwSHcvVnJa
            V1Fmb1dWbGxyTWtOamhyVHlxVWJOeEtVWEJFClFuZmNzekl4UlZxYi9ZdFRjMTdh
            dXJlcEFHMVZWdFdmMHUxRFlvc0F1NFUKLS0tIElnNmxWbWx0ZGtiQXdDYnJmN2VT
            cWRmY2dsQjg2aDloTkozOEZua0FSMUEK3BW33ddqZMYTkZB3r/17DfJRcoK/Vmkc
            ILDEUWX/XTLjma3CU1v1AEXPr1u37e28eDMH1LRRXcYi7LnJcJ5aNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-12T18:12:15Z"
    mac: ENC[AES256_GCM,data:HSKbs5fvlgo3HvX1BVQkmVCXg4zbkP8UFONq5fEhZ5+TtOPk7E+7aAoxC889kzNstWPzgAziG2bT6jZT4iuazn9mcfiBfPWuekvayinLFLLncdsiC4vXIC7tkrBARC7gZRGf/Uw4bqMzs6qGt9oad4ag/Ly0wUle+F2gY1Di2vg=,iv:OlcFvPEYVRh9x1qRFb+aeZXzxZBYEuV2+5LlIUKwPfM=,tag:hX0qfWqjL5/0n6iqGT0cmQ==,type:str]
    pgp:
        - created_at: "2026-03-12T18:12:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DWp+nDyPN4uwSAQdAeHgX7uiTX4iIrdVtMt3acPcqV0X7gLDqlU48XLBLpyUw
            LLmdpgcVYGz6iy6Tboj9njlzBSoNHDVlF/fYJEPK15omfE3/uA19PHTgRtEmSblO
            0l4BefTuI7gwlINA1CQAS0blS2aW6VS/8E0S01N8ajmlDbgITUZbZqZrjQyhv8If
            vJuB2aNUTyqDBHYzgTb5by6MAdPxOoD5M0ssD6ac9LG1RdcqG+UGj6DsMOoxbLUJ
            =p0ps
            -----END PGP MESSAGE-----
          fp: 2EE325D71601671696EBF687E45953D34C8829ED
    unencrypted_suffix: _unencrypted
    version: 3.11.0
