seed:
    cache-signing-key: ENC[AES256_GCM,data:xRwLPwYdXtoq3fnToXCmZmACW6svN7mrz3j2Qhnr65geUjYVJD2ndn61X5QCPosCh13CFkJRgfMuE2Xkk+XNrf4JFUcLk6veqWhwJ7ZWIdyLLqWh9ZFh+1z32QI3+9b2M+bySeQ=,iv:qex9mbTCrp2jMmzLyrvkV/rNWKqsugNS8Zc5RGjr2zs=,tag:/+erbCgtmVW7mkE2IDhi3w==,type:str]
    s3-access-key: ENC[AES256_GCM,data:BXd3m0YGK+ES0rlMxH4RbgEYhaI=,iv:KEQrIzgEgiYiN3jLi46RDuCeNKHaQGnNcy9EsmeE6L4=,tag:BSK/3hXc8rs0386wvDQ1Ig==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:8wxGwyHd2Ck2Q8zO0lh6nofC6H1soT/sLTln/907gZnhAdx9SLGnNQ==,iv:nEQYBppylQOyC6Mi5XIaFgjsAZAag2E6nKWbdrVIuyg=,tag:N6HVcTXD+gIGpMKZZAoxmw==,type:str]
    controller:
        gh-webhook-secret: ENC[AES256_GCM,data:TkhC4+SHTHcqxiGvp+twcpWoS3S4KZ56MiOozkJF/o5hDzr6meIlxqYo5oU=,iv:M9AHvwY9eZNzXgYKJLnAJU0gKzomvjNfbELeaXwJ6oE=,tag:B8ihAOka8lKxzjXEbWI7FQ==,type:str]
ceph:
    mon-key: ENC[AES256_GCM,data:8QNLuDieXVboV2qw/QR9790ipMhzBVZkCsUVX/3jrKr+rhQ5uZ4s9A==,iv:cNPJuGd3h5IFQIi7LOTULapyH3vE/RWnKZIw7NwCKU4=,tag:TUmtzJxNonEmJwAJMme4CQ==,type:str]
    admin-key: ENC[AES256_GCM,data:vdnRZjlrAPd+jPMquATqQxLwMEclqVRO7p1yvkoo+FpdrDQ3Yst3EA==,iv:MNCpjvp79NBBClr9XgAHRqPNY0hTs6f+DgNbtrmJwbs=,tag:FzxLh+QHpt2rWWla2P0iMQ==,type:str]
sops:
    age:
        - recipient: age1uzdjpvu5ftf5um2veavl85r2hht89afk2l3sajxj3ehc7wa9ya5s9fqlrh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4VGNZQ3d2Ym92RXRocG02
            YS8welFBRkdOREJRNFpNZ1lZSEEvRXhMVmdFCmZOUHB4cm1lUjF3VzVtcGlQM29v
            aGJDa2NZSnZ0anJLNzl2Rk9sckVpUVkKLS0tIHh0Q2llN1doVHpMeU4yRGZVa1VT
            TkYvVERjTVZzSTRRWmZnOXJuckJ3Q0EKzyyRdzgtd6azfSeRFkZUp9UbdIsOa48G
            v+bXkQdthyQFwsxxmbx1b0paET5h1pyufuOl7aoLevaETkFPiMwjUA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1neey2tjnrka26dndtwp400y5auud86v92f09srdr3xun80exv5jqcnlq6t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaQmFIcWl1ZEIxNnB3UnZk
            azdPK2Qra2FYSG1RKzlBZzB5ZGxWWUNwT3hvCit5VmdNYmNRT0luWXl5Q1R4MnBW
            WHo4VFpNTkV6UTAxRTVKd3VpTWFadXMKLS0tIHMrUGdJQm5CckVIS2pvQUxUa1lF
            OXZzQ0VnNmpFZVB6VHM0WFZPWXphWTgKrAdsy8TXFLTWHPa1FiVPC7HsOt08ITVl
            nVkfpcG71dQb8BbTSUUVo7Q35Qb0gIJh9D74REXyAFfXqa8ojn6omQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age16kvu4zv76gnuenewe3eaphx5uq5xd4hcw9qpf6x7ltgtlsm9kp2s05uvwy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1dDFIS0YzU1lLaGJmZldB
            azJFK2l2VGZ5UVpReXh2V1hIUm40OUZ5T1J3ClNIS1dGckZjVm83YXVKdnZBblNi
            YVRTcUVMa3Q0aTBKYkJpcFZST0FnMnMKLS0tIHROR1BsWDFEWjRHMVdINzNGSDU1
            ODQxaS91a0xDdUJOZ3pXYjlRVTBXM2MKxIrdRFV0dAhT95FkQKXWfFMsjYXnVdEy
            x/r/s4P4oD9T2NVqsbS9jqmTlFoAbnPpOKHpWYZwnvX0HReiVaiC3Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x6fmwskwxvacf9nnsafexvpgfdl9ugj9xf9fvpvfng3rkukc3yxskddr3p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBabVB3cWVTWnNDNXlOMzRS
            ZlNmc0tRQXRGVll3R1VMNzNGZndtbUFmd0g0CnRFWFJhTFo4bVpxRVNxeUlyZ3lV
            byt2YklVS0Q2VmVEL2pKZEpPcFNzcVUKLS0tIGRkZm5nayt4M2pmSWJqNDRwZFVM
            UEhpOC9WZiswenNtbFRxcnJnS0k4bWMKJxiU28CATAeZ0Mm1xU+rkvVfm4jlQgCd
            LdMLjH+I39ePSyuYb1iZdj+YXi59sAZFFNPW7X/xM/GG27y1oDA/WA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1s3qkxjd29dd6mvttvruf6mpzue2lun3qmyfnycgk8t6c7ftz7vpqa87flk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1NDVqRWIydEpZOTBzWWU1
            OXpZSG4wMDcreTFKdkV3Q1pqaEdCaFYyQmdrCndsYURhNE5YNENXMXFwZERsZTBU
            b3YweEZkdnFJQzJFSjVRWnRlRkUxUlkKLS0tIGw3QzIvVW5lbGN5NWpIM2tJeWoy
            M1lKczVKWXZTSmhsUFJ5ZTN4cis4enMKK+Y98VTojkS+bewdVs0JxXOblE6Bxfyc
            hGthp9qUbviWXFFyAJawaQ1sgNppN1Nl1qhpi1KPiwcdkN6puO8OQw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1kazl566j80pl3eshzqv9c0wyq843g8ep7vt27su03e4jg6eg64gqv6qnwl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRbU5PNmlMVzJHOWdTTDZk
            aXRIazJyUHVHNlhneG5qUndKTTVpSmZHRjJRCjdXT0pGbmNoUWI1UTV3Q3pQY3Q1
            WTA1b0duM2VWL2daQlFOVG9ML3NPLzQKLS0tIFlmWkxqbWh2Nk5ycEkxR2oydnp6
            dHhoU0RGbkxNaElVaEZucWtDV2NBWmMKLTyDaLWt3Tkgh47oM77PgHDaHpojZmol
            pH01qbK9w+oeDRoRrkFep2GRnSXbGlaraw6eVuYs1aFB49r3yee2CQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ujjm7feyd3p2e0qtfa6zr2rzf593yd2z0xjn0ytvd8jcje68nansxy4zuu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2Qi80d1RFVkVMR1VsaTdz
            Y3pXdjMwN0RYZ09rd2h5a0FEMjYxSUJKZTF3Ck1TYzdzWVRmaGtXVnlXaGtIZFZt
            KytuYjJWV203dUpQdGFEZ1E1akhkYnMKLS0tIDVZb2p0TkhmOHhTSStJWDhSbG9B
            UGJSUHBaaFhEZVl5aHV6T2JFNlVIRmcKA2gs0HpVvB8Q6fy36Ldr8hHhkn5UGY+2
            rJIYpPfB6I6KE8UbhpfN8fn2gZUljHSqIDuhnVlSa2TK6HxUwzQ/Lw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-14T18:47:45Z"
    mac: ENC[AES256_GCM,data:jQ2KEeCKZhZhQmarSMyV2jEuY6cGsuNKUIrbsOiCQipy92VX0CYBWZcvVASVd0BtoxoocT03dYfO2Ocs+dKpbk8rRpMYQyHgpMm5/Uu9hJlDm8xxlCJ4J6prcM84BqYSvaM2AoCqgRE9o1g3RVvMYw81vxUcIizI8e/2OCPhHuU=,iv:J2El/8PpiRcfBPpAKH35xERKfWSnTe9ed5Eg1Vd9H7U=,tag:Fk82rp0DgyEB6eeT79vDNA==,type:str]
    pgp:
        - created_at: "2026-03-14T23:49:06Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DWp+nDyPN4uwSAQdA6C9cyTFp6TxqvQhjTKFrLHE7XoXft8ceSPY1Bd0EKyww
            2SJk2ukse1X+w2z51bQ1QLf/ebeOiyQLEnbBcYGncITP7QRoS39sS4EI7f9t1Fwu
            0l4BTwUZu+Vz92fFR4/wDRKfM4JXI+qrpb87YCqMxAl13v91yQzdnI08slHRGanH
            RwoJorxjzOYt2sL3nUw9SNhI/V/1fvsdZAR76nGl74yDAVUXFSVM174NYXtr50Pz
            =Ol8I
            -----END PGP MESSAGE-----
          fp: 2EE325D71601671696EBF687E45953D34C8829ED
    unencrypted_suffix: _unencrypted
    version: 3.11.0
