seed:
    k3s-token: ENC[AES256_GCM,data:vwAyETHbaWDBqz3FUPm85df/pV8ooZzy1d3A7Wjk3ZWR1+Z/Dujin5yXnInHi9NHvkI6+a/KWQyLqV918j1UjA==,iv:pGXjT0PBuvAoIxQ4mlIBVEEDH/ZfSw74ph+zRCMWd4E=,tag:nJwftKJIlxWqqPZxCSXmFQ==,type:str]
sops:
    age:
        - recipient: age1gcnvkfuptygecafugm5m54cfh2krnh95x023w9pjyj4uz2pu697qwv7knd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTd1RnRHd3UDRhcGtIbVF5
            MTIrK2pJcXNkSlgwTU15VkswN2gwNEhIZmhRCjdXcjZWMGNIM0ZFelhXdkMyZ1Qw
            Tm1JL05Wd0dhTTVKWTRVRlVxOVljRTgKLS0tIHVsdFZHdVBrYUMvVHRycTNvYnd1
            cGhrUW1iakpDZ3pvQ0I0RkgzbTVYWUEKYCF9RICT5OYJ724rxR+ThcpJDPRqtnKF
            BRTc0PAgRop+2+sluMsiaL5tCDyMQYwXPXl4zZ8SHmoa2x433bWfqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T17:59:09Z"
    mac: ENC[AES256_GCM,data:mcGIFGmbTvwLMuscvfbxUKt3LdRX7//4jN0YdIvovIh1re44B/Yks/GwYEIckE0w86xNKCXTTyF3zj7rqB02lnYTTfk5TqCr/vw3PEdMkgnG26e8QEDGyh/2igVItKjwaeanGVRwdBgakmO9lNOwuDYBxSal3/S1SOoStxVphCQ=,iv:amx+J1UPZeT9gbJ7LrmSR0Gm8q8ub1cacSJr3BuCPyk=,tag:wmOFqn7xxlrs3pbumiJikw==,type:str]
    pgp:
        - created_at: "2026-03-10T17:59:09Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DWp+nDyPN4uwSAQdAgiOm5rzTSA5WU6ZpgCCXjzcFIA0rsC6k+9tX8I0K4S0w
            3TRCjHNG47ClmhDI6ZMiqRhTpEklIFUSjWSIYnAfji4G3UGQuflJoK+/EoxeoW2H
            0lwBF4w37jrjUXeDh97p28Il1QEb4sIH4DtdFQ73RS43Ky4UYRWn8Mya9UzWXB8J
            DxgErvmRFHCMJTUda3FKbciqppGyvff2lNv5X3DCfTh5nHsO+U11jqEislc6nw==
            =DnPX
            -----END PGP MESSAGE-----
          fp: 2EE325D71601671696EBF687E45953D34C8829ED
    unencrypted_suffix: _unencrypted
    version: 3.12.1
