seed/k3s-token: ENC[AES256_GCM,data:sbKOuCKrqk5BMTe67Xbmr1oFtsGNemfz7K8VX6RW4Wo9B04oMLunWewsTZbW1m1J5qXaEhMC8fwpFMK1bJvZhA==,iv:a9e0D1rv/eGG5MdAo0B94aGj8k2MhpwfegwMEXRujlo=,tag:rrFa0WetaWwlE9SVqYLTTQ==,type:str]
sops:
    age:
        - recipient: age16kvu4zv76gnuenewe3eaphx5uq5xd4hcw9qpf6x7ltgtlsm9kp2s05uvwy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5bkJ2SkRwZ3FCMU81M1Bt
            eHYzOFhXZEJ5RWttcGs0eFYwOEtBN1N1SlNRCmNXK2ZmYjRuK1l4L0NRaUFnS25i
            ektzK0VpajhIdW1kUnlQa1RlNGt3QjgKLS0tIGtOb1JRZE5idzZiYmxhY1RsR3Bl
            WkdHdWRCVDlrc2JCSldtbVViQ1Z5Mk0KW5Ui955SDfi0uxBIPWT911VJqhB5yEaX
            1wS1K/6ehCZ9rnt1X4TG+qGOVqCwWES/gytvXE4+0FJ1D4xmQDLVqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-13T03:41:59Z"
    mac: ENC[AES256_GCM,data:rXIE9u88KOKnWwb4HjRV8VgN4AkPudnLQmo7OFUbp0N0NyrEN7kP7pqX7oWLELFAGMrkyG7ULe/Qm8Bxx/Df9YzunWQm+lRT06AkfiQZxZGAefI0hVhqQZPOJzIjyZD8qO1iZ3147lwZp0UU+yN0hUMhssN6G3SOXNTZ/R4Ghz4=,iv:wBfgQbTVbpKuPk/QFUCrdcEf4yGGmTBIzBvD6UBp/xo=,tag:IqF9ma/EHq4v2iK2G64BPg==,type:str]
    pgp:
        - created_at: "2026-03-13T03:41:59Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DWp+nDyPN4uwSAQdAsghiRw6IcjP7a++K1Ed5J1q34vLoVuoFD2ijlJFS138w
            EU6hQemy3pu3vT7rQD3gXA/8VxOtjDIFAJ7Djee5q4ZZRSGdxK72sTY+445yYGW3
            0l4BeHNY25Nr2ngnXejgiTQGCwqnQ3rf/vCqvC85ZBPHU0vUw/Rzo8/8SXiYmNNc
            94I/crYZM/6wtZKP30SSLlUHX44JCK+44n42WRfzzIxhsRgstq56VbRhMiF+XWde
            =/PoW
            -----END PGP MESSAGE-----
          fp: 2EE325D71601671696EBF687E45953D34C8829ED
    unencrypted_suffix: _unencrypted
    version: 3.11.0
