seed:
    cache-signing-key: ENC[AES256_GCM,data:xRwLPwYdXtoq3fnToXCmZmACW6svN7mrz3j2Qhnr65geUjYVJD2ndn61X5QCPosCh13CFkJRgfMuE2Xkk+XNrf4JFUcLk6veqWhwJ7ZWIdyLLqWh9ZFh+1z32QI3+9b2M+bySeQ=,iv:qex9mbTCrp2jMmzLyrvkV/rNWKqsugNS8Zc5RGjr2zs=,tag:/+erbCgtmVW7mkE2IDhi3w==,type:str]
    s3-access-key: ENC[AES256_GCM,data:BXd3m0YGK+ES0rlMxH4RbgEYhaI=,iv:KEQrIzgEgiYiN3jLi46RDuCeNKHaQGnNcy9EsmeE6L4=,tag:BSK/3hXc8rs0386wvDQ1Ig==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:8wxGwyHd2Ck2Q8zO0lh6nofC6H1soT/sLTln/907gZnhAdx9SLGnNQ==,iv:nEQYBppylQOyC6Mi5XIaFgjsAZAag2E6nKWbdrVIuyg=,tag:N6HVcTXD+gIGpMKZZAoxmw==,type:str]
    controller:
        gh-webhook-secret: ENC[AES256_GCM,data:TkhC4+SHTHcqxiGvp+twcpWoS3S4KZ56MiOozkJF/o5hDzr6meIlxqYo5oU=,iv:M9AHvwY9eZNzXgYKJLnAJU0gKzomvjNfbELeaXwJ6oE=,tag:B8ihAOka8lKxzjXEbWI7FQ==,type:str]
ceph:
    mon-key: ENC[AES256_GCM,data:8QNLuDieXVboV2qw/QR9790ipMhzBVZkCsUVX/3jrKr+rhQ5uZ4s9A==,iv:cNPJuGd3h5IFQIi7LOTULapyH3vE/RWnKZIw7NwCKU4=,tag:TUmtzJxNonEmJwAJMme4CQ==,type:str]
    admin-key: ENC[AES256_GCM,data:vdnRZjlrAPd+jPMquATqQxLwMEclqVRO7p1yvkoo+FpdrDQ3Yst3EA==,iv:MNCpjvp79NBBClr9XgAHRqPNY0hTs6f+DgNbtrmJwbs=,tag:FzxLh+QHpt2rWWla2P0iMQ==,type:str]
sops:
    age:
        - recipient: age1uzdjpvu5ftf5um2veavl85r2hht89afk2l3sajxj3ehc7wa9ya5s9fqlrh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIejFGK0w5ODlnZ3FzUmdr
            UUJsUVUvdExiK0RkZGUvR2QzNnFtUW04b1FzCm5iWC83UDllc1pDckFXcTZQS1cy
            N3hPNnArOEpGOVZjWWllNytmcFhzZ3cKLS0tIFhPK0hDWjRvWnFmZ1ZtMFQ4TUwy
            enRWZkdBNnM0d0ZQR1JRSHBpcVJVN3cK7SKPqK5AV3ycHztZl78zwzUvtNFNfpxi
            wEd3t7sVuSmzxwCzEFgxWvsbyKCa1i4/MEjbTva/zQIk4uOcuvEkRw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15qrgp59tesw5mjjugrnq096fwdkt3wx7szazuauy5wn7cql8fffsx8hu54
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArTzk4N2FPMWErYm9MVDRZ
            MlB4eFdqdmdwcmttSjRsUEgxMVdycmtuamkwClZVTDg5L3NoVXEwUk9TamhXUTJF
            cU52QVZmaTIzTVBrdXRBN3pkamdsQVUKLS0tIFE2NjBhY1JOSm0zLzNiOXpXQkdE
            VU9Eb2lqb0RVekdPMDVkMWdTaFYrZ2sKnSu0aIknQ8d+SChZi0Fme8OmqguQLJxh
            LbZC77igz2G6+YC7IhhAeX4qmiorvtj9vOFAlefnC4n9bZnvtrzivQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1n5x4rwnefx433nqs9ld72z0947wa6t4zyh80s7ypga7wtrsjfe3qwsvepa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUZmljUjlFWVFwN3lTTjJY
            S0pjVkNpcUlxMHNuT1VyUFNjeGxiOVhpNVc4Cm12a3ZPWDBzbW5VM3IrZk1qRDdG
            Y2ovMVZwWExKejVUS0FpVEN6UWhTSlUKLS0tIFFaNzdCZVVyNUtvL3UzMS9LaFZF
            aG9qSEpaRmZySGpBWTlMNjVpMHJ1QWsKkyC4KYMh7Nd1sZz1e0AXdKmoXlD/409i
            b2IeuHOIhiiQ51vvYhm+1ezR6To3sOYdkE00WYtRtxrQGUHMjRxNWg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1maf9p3nxzmsc05u44czxc5g38j8du68tuv9xnazlzr79vmc7fv0s6udkvf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhNndqRlkyQm16a0hCWFpG
            dDRUM0dvZzBHNFR0YjhVUjYrTVNQejBGbEE0Cm1YZVhoeVlFdHpxbjRzSUdKWm1I
            anlPWFc4QXRuUnI1c1FrVnA2cUdHVkUKLS0tIE05K3c3OFZVTGxtdnFwY0NlN0VH
            bTZJMm5uNWJhcmU2akZWUHJwUTJWNE0KbDvoiWJcP0XmOmS98dG3DmEYfK6r7h70
            7BOOYd5QLsT9al2ZNQRvk7jMXWdMwzbK5R5EhJ48BlVQbBO/9hZYcg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1s3qkxjd29dd6mvttvruf6mpzue2lun3qmyfnycgk8t6c7ftz7vpqa87flk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxRCtCL0hQcjZKTGt0WTRZ
            OXZXUkNTYzVoSVAzSng2aGZQYStWd1piV1NVCkdKaHhkZ2U5WmF2M3pTT0Zka3Rl
            SEFXOVFBdmloNDcrNGM4NDl2blJLS0EKLS0tIDZoU1FjRCtoYURBZ3dDK1R2N1lu
            OXl5b1d6dTQ3NHQ2UzlOanVFNi96NFkKaDpmN7aAkGIJDBfbUMfRfYFnTtPKcRMA
            XaK0SVG1zZbv9tfO0pP6ebsP65YAD3ENtl3UyCqULhIxM49aFX0RAg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1kazl566j80pl3eshzqv9c0wyq843g8ep7vt27su03e4jg6eg64gqv6qnwl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQd1BPTU9UZkhmRER5dExU
            dTE1Sjg3VUtYNENKTzBYcm1rV0kxU0RaV1EwCndpeEdQRStQTUk0NGVTSSt5ODdi
            RGs5Yzc3MGI0OEo1cFNhM214MVNCKzgKLS0tIHJ5cTB0VmVneHRtalBUbFIweE5R
            cE9JclN2OStJWkZSbzhCMVNqMWcrWWsKLK3ze9DwjCps/N+OFPkHrL5GucPqmUr4
            pCG13/sXAT+psrJGFyDu+L59XGTPLqoW6a+HDMA826p1fnfyr8OAjQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ujjm7feyd3p2e0qtfa6zr2rzf593yd2z0xjn0ytvd8jcje68nansxy4zuu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoVk5GaW5jcHNKMG9FUEUx
            WFNEc3I4YVM5ckQ2WHIvZHpmc2pFU21vaDBJClArREtyT1pVUG9DbTlxWXJiM0U1
            dmZFenZSb0xlS0F1WkxqbmR1bzkzZG8KLS0tIEVPT3lKK05TSkFDRmNKTTd0RWtv
            TC9wb3NYV09Pb0RIMTVBdmlRN1A1NGcKxYr04BMirjm+JsnxI2X4uMyLYVN311Ac
            TfbcRa+BB0kmzNuB7Rn2FoQHPf9EIT8PDrQV4y7VsJtHCKVGeHBdzw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-14T18:47:45Z"
    mac: ENC[AES256_GCM,data:jQ2KEeCKZhZhQmarSMyV2jEuY6cGsuNKUIrbsOiCQipy92VX0CYBWZcvVASVd0BtoxoocT03dYfO2Ocs+dKpbk8rRpMYQyHgpMm5/Uu9hJlDm8xxlCJ4J6prcM84BqYSvaM2AoCqgRE9o1g3RVvMYw81vxUcIizI8e/2OCPhHuU=,iv:J2El/8PpiRcfBPpAKH35xERKfWSnTe9ed5Eg1Vd9H7U=,tag:Fk82rp0DgyEB6eeT79vDNA==,type:str]
    pgp:
        - created_at: "2026-03-15T00:05:08Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DWp+nDyPN4uwSAQdAO/erfeCw7k15yuGFdTN6syEHJeOjcOZBpSl47+p1EDMw
            j8iM5jFLhPKL8RV6/Cmutgg/NGvDoAgckzaz3BpBDN04jfakKKiLltbm2MjkoHmO
            0l4BuZY5NZZgnBowtz2SCnVAG5zd6wG2ufVVs7kXM/cgahuHc2d8Fbe33BDfa+A1
            YUZJNwAUKrmfgzsVBMyDMAUL59kHbJ1ACcDkhzxgLjNv76kg3M7T1Rxih+SQuv/n
            =vyKJ
            -----END PGP MESSAGE-----
          fp: 2EE325D71601671696EBF687E45953D34C8829ED
    unencrypted_suffix: _unencrypted
    version: 3.11.0
