seed:
    k3s-token: ENC[AES256_GCM,data:OJHVoY7xmgcryFTSoG3r2jwbprG0TJpZD/SuzHxIbymfG0vlkXh0w/5wD3lckS4RbHf8BzWa5OpHY36vhikg6g==,iv:/qwEF9d40R60J23R/uuOLrp/4TqHzW1VxvuXflGbxLk=,tag:ZvQO3RwKUnDbPKklCv2gLQ==,type:str]
sops:
    age:
        - recipient: age1nachhe6fxyqj8wzzypxg7lh8utg2pdn7mrg5jty77keunemcau8q0pxnhx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCbTI4dlpHL1JyTTNscWpv
            Q2orWHlxUlBLbWg1UHZoMlk5VGNRNnhCaTJBCjl5aEZmRXpPRVRjUTQvQXJKemZ5
            ckk4b1JIOTJmYWl2TVEwQmlDQUEySXcKLS0tIHFtME1EN0VhVnRIcFYrU2lBYm5V
            WTVGa0kzZjhmQk12amd2LytGUXJqaTAKfc3zpTMSKB1ddgUL4M7OG+aafSRMsMc7
            kwfoXlh6tva388wep+Zcg1j0vnP/5qztnpmOYF/RVBzppvNk+kcqAQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ujjm7feyd3p2e0qtfa6zr2rzf593yd2z0xjn0ytvd8jcje68nansxy4zuu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxaUpWZGU5eXBMU3ZGU0xT
            UzZ4WnlDVzRURit3VGZudkNPT1ZqTXZjQUQ0CjhiRDhybklEWk9kK3lSSzlBZVNN
            Z0lUTnljMTcrUFl4aThtQnY1dTNoQUUKLS0tIDFleHl0eTRucTYyRHVYR1RjRkJt
            Z2hsS01pT2FUMlpKdmlqTWhPTGFNVGMK1I/tzXKghGfrdAzYAEslF6JSjGoSa+1e
            2mUs0WolV2gtrJA+piQiz2uO59aB2Bk9ncS9UrbSvl+8lQc9dgkZoA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T01:19:50Z"
    mac: ENC[AES256_GCM,data:KBLX13yyhFAB5HsvBZSH/30Dkor3ij+AXggyS6FSJtdBSQQL4mp+iqu3Lai28eYly9ks5c9RiBecUhrEB/pDx8yJ8IUJvKa3nDDxg8qxUyXtL++TQK+rzQZq79XLumWcKmGVouUQIgPWDvQk0O7rzQBvGLZqKWq2P4Z9XRXd4rQ=,iv:ThsFpKX41KekgvMEy5jiB9MaKnrdr3Gi4X+AhXrbLu0=,tag:GlwXnYygfv9u2fQqSik0yA==,type:str]
    pgp:
        - created_at: "2026-03-15T01:19:50Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DWp+nDyPN4uwSAQdAD5g7EYDk6hOqug3ZonP/udlz00Mjg6vbOb3ni7qVGE0w
            8BCjydF4UcAU6owUQlGmux0Nwexs9lUGIkFrq8CeyTBAhgDqFvYj3hdsNgPgT7+a
            0lwBmSCZ10H62t1iyzwB5NRUxnJcIXqzfS/OGJq9F6wyMiw6khVetXXkGIKaY9L4
            kVQ8aYzLKmvVFuKlOb9bSUmnUKkHbwN/VP4BnZiboXuKoZEfk266Bb/hHk0fXQ==
            =Vf4i
            -----END PGP MESSAGE-----
          fp: 2EE325D71601671696EBF687E45953D34C8829ED
    unencrypted_suffix: _unencrypted
    version: 3.11.0
