seed/k3s-token: ENC[AES256_GCM,data:kUGVnIUPJcbnIzoEWq9xnfkW9sOdBpnROovhxAG092NQFb07zaIk+KDKQAXvXntpaTKLE/dv9E90f4LJ5uycrA==,iv:Xk4dBHsFRiG5MO30QW092+zEAtLbEpxNvb1md+81zo8=,tag:QGXiEXUsKcxq/ulhq55dSA==,type:str]
sops:
    age:
        - recipient: age1x6fmwskwxvacf9nnsafexvpgfdl9ugj9xf9fvpvfng3rkukc3yxskddr3p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjSGFYTG9vek5NU3JUSVZV
            YjlUdEZTbzhSdjg2TWxrRFkvZFk2RCs2NUZNCmVHOWlXM3VGaEkzWWU0VzlYdmtt
            d3dkOGE3QUk0dXpmdFpBempINkg3K1kKLS0tIDd6ZVNWeXFLcHMwZFdJR1NwZGVY
            VDhlc0J0di9tLzh0OTZkYmo5Q242OTQKADUUFArq+ae2wY4T6p0RwozU9L4mjNs8
            x3mFBhD6ykSO3ctEKX8e1IgnZ5ablnOiZv3O/bdNzXixggrpMwdZxQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-13T03:42:04Z"
    mac: ENC[AES256_GCM,data:baQK0PtkRUnD96KP6zU4X3eYSmNfgqGQPcAcFUd93h3X7JRbkiM5wH4POVus5naMyGuhsEYHswaRtFNmH036gMtnf62SWqV/Rkig39I61EMeJNHCX4+p+qS44C65Iduhi4xRl7NuH5nAsN1gMXRyK9M/k6r/0g2pbZUBV3XFDUM=,iv:HVyxxnz5yZ7cp7RqnUckGtroC8T74O8OdZcgJBD0UDU=,tag:5clkhZGBQT1fmXWF3IbxCA==,type:str]
    pgp:
        - created_at: "2026-03-13T03:42:04Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DWp+nDyPN4uwSAQdAfNzXw9ge7b1X06JRYwKtpxeVjm9yW9Y38PCfKeFpKV4w
            0JVVPIGYTC712DoUpk/yU8B26UGT96qOswwuGYay0c3vzPtKbPkwH74D3LYfNcF9
            0l4BiqNr4ROKD10E2avy3uL9e24Xgo46ZlKgyEGerOjhpDdLo4UZkT5TMPOnVCMK
            WI9u4X+A2K3ruICoaX2lsUyzcjW0RqRUse5fjFcDEj1YHvlXNIJc8ZYx3nbeKnMg
            =J922
            -----END PGP MESSAGE-----
          fp: 2EE325D71601671696EBF687E45953D34C8829ED
    unencrypted_suffix: _unencrypted
    version: 3.11.0
