seed:
    k3s-token: ENC[AES256_GCM,data:APb7dNFJvSVs+dZ9NUgPIc9DGHFAje6Q/xiN0g7a8kk2mSjEt6cGTLhbuGjwf705mO9G9zsGMqVjWI+2o6DBKA==,iv:QGVv949nMVq8zuA+hvczCiLnFrF913dWSI/Z+y6Ig6o=,tag:9AxAwRI1mHjxx9Gtw5i6dw==,type:str]
sops:
    age:
        - recipient: age1maf9p3nxzmsc05u44czxc5g38j8du68tuv9xnazlzr79vmc7fv0s6udkvf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUQ2Ric1NBMHpyM0JsMWNx
            S2JkY1IybjRzdktRUVliYnZJM1dKYjdkOGlFCiswV3dtcVd3VWFKQVNDaGV4YUYr
            SVdCL0ZPQmFiNXJ0T0x6VlNoR25yNTAKLS0tIElFTjQwMGNxVStOUEZtdFEwUVdy
            ekJlUVZaZE82cHRJNjNkRFhqaEdzakEKNclgV57J7r4At/60eR0Iwsu159Gc1xgT
            M0sXXVIoRJizWAkQzIU4srWX3Zy4QEi/broltbyEN67yNiOCfRWGWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T00:05:03Z"
    mac: ENC[AES256_GCM,data:XB7HsgQdBRK/c+/o1DPbyB8jeMilp6hyEoubDox+wWERA4A6yp5oJ183LBrcQfrIcdWpPKaHekHJvLYwqijLN9jL0inEgAFnyfc75HNr/GOiJKmRE3G2HYLYeXFw9rmaaYdxladQBN1zYNYT7QXXfMavyRzehlAeaDU0g+quuFg=,iv:M1X+9czbBEreyK1JUo3do97Zv2SclGYpcG78yabpaGI=,tag:Fbdwnxyp25Xme9nk+HXc6A==,type:str]
    pgp:
        - created_at: "2026-03-15T00:05:03Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DWp+nDyPN4uwSAQdAC7aQDu/4QMD3xRnrZzlbfw/C77bWy85MtqGpFrkTq00w
            Pd5r6HXQeUhY8kDPMvJiday2Gm91v8r/uJRpRz0SHiCMVOqm2f0gXgj7jqvwKgJy
            0l4Bl1ejsJDLCDh7U5s3RH/sGLR6LHEBUlfmJyb1+aT1T7sp4Q9GiJTe9toejH9f
            AgPiTTMQqsNfElEl4Ca2mFbLtaXbXGebIFib9HDE/uSX0AiWhQBK9jJkSlnYfxIF
            =eo6h
            -----END PGP MESSAGE-----
          fp: 2EE325D71601671696EBF687E45953D34C8829ED
    unencrypted_suffix: _unencrypted
    version: 3.11.0
