seed:
    k3s-token: ENC[AES256_GCM,data:0tbmrnQIVty3E2KmvV68fCK2rXRtE9HRKByZ85riD9oLcgKhkC5pm4SGyzleUAImbo3Ctt8bNTUPV+ZscYSiwRtPFR2boIlYMUledjSpUH04gyccO3cJs8iSLjMsa/CWMkVod6l1SccPZqV1smYVED0BDzY7CSB1RT4EYpGk7STyqP6tc/crJ9+1aJ0=,iv:+HZWEivCqpRUsRPLWusjHLIO6icwgTC30RPsFeUpHgE=,tag:HYlRxccIMg5T/sBPD9l6TA==,type:str]
sops:
    age:
        - recipient: age1dql0yg48r4m6xsycwxf2dn3wrvdld6rrszgm2yaxud4jwamx7vgq59gxy9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBeW54ekVYb2NRTHRDc2Ex
            RGViMEFPcUJaR1Z1MTdQLzBWK1VDbXhkUTNVClVLaDc4QlZXVm1DV0lkL295MkI3
            eUZ2cXRSeFpYaFNVL1J5eS93YjQ3WlUKLS0tIEx2ZmlVdUo1T011WkZoaTRvaEdZ
            MzE1d0pYRzdhMG1aRmN1NGQ1MXIwUk0KHxGVWiefKuz16TCKqS5Mb3/st6xjoObU
            pT6AFqctwghVY/epZKv1HP21/4tFkw6wJNzkCDr8TEFrUwFxj5Q/gQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T03:48:07Z"
    mac: ENC[AES256_GCM,data:KhI6xnkUe/Ur8f4FLBNANahzIRbNMFMrkeQLTUYySiYk/ycP7m5ElPDSQKtLEvRQD4qDGFEKFO3YPPFVtggw6GKwVuTFhvl9d/87419Yoa0hZrAGb5N1DN9NKxaYqglfzQWSpNmB9O6WzLSrM6mlGj79Q3HFDIGJEiO+zXh39Vw=,iv:8TU5TczmzV8H/zEwkrx6qZa5n75J0oZ6FlbZ0dUZ0YM=,tag:xuBjiAS7E7MUgKLcnKPF7Q==,type:str]
    pgp:
        - created_at: "2026-03-10T03:48:07Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DWp+nDyPN4uwSAQdAB77QNUQAkporUbQK8Ie5b3g7rcPjsAzRCmjSZ0ZKOmEw
            NDp9Ped1urJ8txV+k9YErQEagr2cG5KcTAWvHK/jPk5BERa9lYe7clFXTatX1R4w
            0l4BQBlx9ZblkpZKghZiEyWUxckSW1K6z7f7HMYQYuQ4ks9AiroeRjLnH4P19RnZ
            IeQdX3apD7KjjCaXSVQdpdFucx/tjKzoy+IdfZPSSMpUQovYDAHTyzoWwhRdrohI
            =/YFc
            -----END PGP MESSAGE-----
          fp: 2EE325D71601671696EBF687E45953D34C8829ED
    unencrypted_suffix: _unencrypted
    version: 3.12.1
