seed:
    k3s-token: ENC[AES256_GCM,data:XCSbQBH+5LBcROX/TOlR0Jp7PeQIVP7uT7+k4gtZgVaJQyFYLmCvUOdeqK96HhIuhuIhc2c4qRXcwQBX80nhVw==,iv:Tddv3XJ0CMw871I1zshY5wsdQes+iqwS2FzAO2to5+U=,tag:jjSEOmW3IReRLdhm3C+Qng==,type:str]
sops:
    age:
        - recipient: age1uzcjxhj5jnu0r5h0q8cqf7rj4tzdcp5zs6xk4rv0257n32pfxvysj7lvm3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCblVyUEk0cWNYa05DTSs1
            RzdXMHVLU2JZcE5VbHppeHo2QUlqREVvempzCkdyQzN6T2c5bTJRNlluRzBOWkh0
            MXJvRkFmcnByMFNlcDdkZWdHMDFNR2MKLS0tIC84OTdUS3N5VWhUdmR0V0piNnAr
            cE1uOHQyaXJ3Z1ZIaWFLaytoQ1pQL3MKf52OnK5wilzaGHni2HfisZuMoK1V12xi
            Y22iSmZMUIxRVf21n3nvCZ6PqJjyp+IFi7vAw6DyteWDgXfb+6g4dw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ujjm7feyd3p2e0qtfa6zr2rzf593yd2z0xjn0ytvd8jcje68nansxy4zuu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlbEcyTVI0QTJvZGpaOXpB
            K2s4bEhxb0k4OUIxQ2taSThIbGVxTUIzbERNCkF2MDU3WHlhQzV0SXBTWW1FRWNM
            NkFxNmFnOHVQUCtwTC9VN2FkRGo2R0kKLS0tIG5BVHkrR2E4S1Vzb2oxMFRqOXk3
            SHMyNWsvTGQyZUV0Y0UySndZa3BPSDgKDQLk7ZiGQm6bOwk4rawXMQZHt1znQkrs
            lHRgzNfPBqF+oHa9tpQKWEj1L29wyog4b2C2KxLgbTZkyg73iI81Nw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T01:19:50Z"
    mac: ENC[AES256_GCM,data:+0xn8fWGqfHAnMF+H9sBPXDx9o+dknF7y/A5vvBDH9ObiX19MvlpWV5axNo4QrY2mpO/PT7ya8VFzY/Kur3/ltywHHTVZT443NmxgOPunW43JoJExMgtyYQpfkTnmfO294Eyx4T0jAJi5YSj0Uz5v0vhtmZuZ1bUvQ6mQY3G14Y=,iv:sFn7570G4HVwwKsp77ZbM4JL98klgx/P1Vs+iTSTH1A=,tag:hk7S8toLb4Knef2vZWmguw==,type:str]
    pgp:
        - created_at: "2026-03-15T01:19:50Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DWp+nDyPN4uwSAQdA3btJeifyCy2stu0ZZjIJnE7x4df8q4+moZtNZxws9SAw
            aUsD/UWOXYAlms7kgCVWdwap6QSwVcU0ISBC2H1aH69m5Ea3Ot7iToT3HXbTTXLP
            0l4BRar857ceMKJGUh5QTlE5fJl9WBham3rJmOZzv68JvfYPcVl7M0N06kE8lFVY
            AhFxw+mec3sehKRUtBCEsUaFsu9TlwhB7JHKOvthR3VdevsmfxDO5zZgtNhLN1iO
            =rB2h
            -----END PGP MESSAGE-----
          fp: 2EE325D71601671696EBF687E45953D34C8829ED
    unencrypted_suffix: _unencrypted
    version: 3.11.0
