vultr-api-key: ENC[AES256_GCM,data:arc0pyGkkkdmvckraW9Ygup/nb0hzFYxLfjLRTnsIuBebUku,iv:6AgyNm0IqOtbS3fVZ5X1gfJjOso6c2nlw8VEkzMMYDU=,tag:sTUgd+dlCVodBw4TmNWY+w==,type:str]
sops:
    age:
        - recipient: age1s3qkxjd29dd6mvttvruf6mpzue2lun3qmyfnycgk8t6c7ftz7vpqa87flk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0NStYWHZ4emxETnJwSURr
            cnpsYUJXZXEvRWMya3UwdURjOG9EUGlxVTFzCllVOVM0eXg5aWJzWEFtczBsY0tS
            M01rbXkyU2RRUytVckhaWmlST0tnTkEKLS0tIGhWRzFSdGtna2Z4bUJyVndOaS9Q
            ekNUSkQ3VzJ6VVRtTnRFRGVkMlBaZkkKleJkiAAk7DDWq+sr7ORXJAnHnv8jxpJU
            4rw8ZS6agNn2bIZb7KQ8PfFGjV0wq8QN1ZkejG3w4t2QQyX4ECwpeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T02:20:33Z"
    mac: ENC[AES256_GCM,data:UGF1q6FSqIcg89cAfaQjpSo3OYkZwKJHmVSlqA9keLpU0crjRhZiQggHS/AkpqzxiUaNzZjJR0GWwrSIxJ7CbnCIiZNYoFNu2n4GLYLVXVExmh23hiq5fqDH3dN1NH4vYOXneZtZ3OYdLlIPhHR4UYGMKwW2mwppaUBt/Jby2O4=,iv:J/LFUD5jvU/fQoS/c1VQlxSjVupbW7LhhSviImz8URM=,tag:o3uzWqbHtvEeo5H2pXSnvg==,type:str]
    pgp:
        - created_at: "2026-03-11T02:20:33Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DWp+nDyPN4uwSAQdAxeAgavt0w67VOZ7v5I7uoaA1qtLJWE2oh2g1TCB1vGgw
            YubvnHDi6MZF3ZSZkeCloz6RZgUmaWtvp57Jq9XySWnis/meehSZdLfAH59Ob/M6
            0l4B6QicCC+ljavNgzoMHRNrtY+KQ1aM1noauRD6hV/MjS5uFcWKKX+UqAOG6nLg
            gfNZNs0zCw0ZkNCbRqb2R0LISII/CZDHLuurxkAdmoulV8UUvd3lRdeEqlO64TWk
            =nKXP
            -----END PGP MESSAGE-----
          fp: 2EE325D71601671696EBF687E45953D34C8829ED
    unencrypted_suffix: _unencrypted
    version: 3.11.0
