seed:
    k3s-token: ENC[AES256_GCM,data:T6AVSqM7ZrlyI82kIYTaT97rKJW5JQtZZfej473cUkRjP+v0xgyKSZXbKUnm71t4N3AmgiPVsKbO2Uo2MXgprw==,iv:+dT+zqgusV/Ia8+v9jnZR1krvel1plBs1rhLH9JztYU=,tag:N3HicvuEbuqRMc8iFA8BVQ==,type:str]
sops:
    age:
        - recipient: age15qrgp59tesw5mjjugrnq096fwdkt3wx7szazuauy5wn7cql8fffsx8hu54
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4d0RXTzFvTVRrYW1DVXhk
            czF5SHhaNXdDUTVIZkNIR2NONThYN1FVUTBVCm1UeEhhZlQwNExnelNKSk9LQkVp
            TC90Q3N2RG83V1A1VFdoanpvWEFqUEUKLS0tIFU4Z0F3VVNldk5NWHFnbW5udm44
            SktWL21TRE9Fd3ZkS2Q3YU5tTkhtM28Kh++uKFZDwOkcR7lHfRQvOyAhbCHybuIf
            lcv0iXTX7cAGBoNsBdEIztepAzDBm42UD8Y4A4q1F4zVmoqIlYH40w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T00:05:03Z"
    mac: ENC[AES256_GCM,data:vyfFOR9NLNc6mnZueMPN0gys/OTTyYTyC6BDKhaOty2qQy+LDlAWnMeoPvVeCcg01vYeVldbWAIrRuJoJSAFYY6BIk7+DdTO80Kh4wiXPz4YPtUkQoiWSKi3Lpn6bW25q062sxu1NnxCNF6tzSbJjRGZMM7fDt047XXNUXLAS/4=,iv:gnx/4A7z5vMZX2REEjzqBJvFFgWlwkh4LRFDnfUrxfs=,tag:UkcgpTGcLF4Bv0cYA+NgcQ==,type:str]
    pgp:
        - created_at: "2026-03-15T00:05:03Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DWp+nDyPN4uwSAQdAoiE0xpHqdljImahiN8oniyyjXBdJbTJEemk245IGLnkw
            ddLVh/cJHTO6OwhKMUXrj8ETCicymzIil5n4vMjGcL09+fzzeLtwuWmS+GdnJW73
            0l4BExcmjr+s1yQdTzd+dmI04jB1k3g8olbXV97OEXN9W/NSCQLPEnPkheKbzkvk
            AMDnLWxGH8cZsdjVn9OYDoqvWGgmEcVTCXvxxVh1FSX3EkPAQHIN7ONaryaVbOZx
            =7j9U
            -----END PGP MESSAGE-----
          fp: 2EE325D71601671696EBF687E45953D34C8829ED
    unencrypted_suffix: _unencrypted
    version: 3.11.0
