seed:
    k3s-token: ENC[AES256_GCM,data:A9KKCG8H5yS3ENPRCBLnlovoQY6Qknh4usVI2HyQ/VOyIL+SdHp1FFEO1W4DAPrzsEiFmIvyZhA1YmfjmWFcOQ==,iv:JYIb8PKSnDK0rERG/3oWSh1YUEm+b5/+e/Zkkb/fgzY=,tag:wRmlS9egNg6Wl9r1cpmdMw==,type:str]
sops:
    age:
        - recipient: age1n5x4rwnefx433nqs9ld72z0947wa6t4zyh80s7ypga7wtrsjfe3qwsvepa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyRjVXaGoxQ3Fsczd6RzVQ
            NVJVdVlwSkg2QUxUdnBMWUdrWGp2YkFiYmhNClA2dkxSN2gwSjJrTTVTNFZnL2lY
            TEFhSnIyNUVGdHhFaE8wU2FkL216UjgKLS0tIDBnaW9VN3lHK2JJMTEyWnRIMW1U
            WEtOWjN0cE5iVW0zZTFhS3dXU2FTeFEKVJHSYBsmIVBwjxQhpci1W0xVBe2EM/rW
            wgXomtRI5WmTr8Ny86Eum/U2d2QP9zipi9FmERAWEwdm3tFmSjXZCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T00:05:03Z"
    mac: ENC[AES256_GCM,data:jDBa6mznQ0U6U8qKTiBGzEES1k/Kjzx8/FTxaSnT3fK+2phcmNjYhWjQINMZoaIds3JQl7Sq7rVP/Wj9Gu1ouIOkunRcJCStjeIjpWlqBHiX5YW5SzvShpA1lJRmfEZ3fked3X+JeQoi52mASfncaIlqIqlFUI0CY9Q3mxGqrzc=,iv:oV+PnwTwG79/+rGFHPckR6EkMTFw6wwOTNGOhLmN9nc=,tag:4jXK5U/89vidXAwIqYLTOg==,type:str]
    pgp:
        - created_at: "2026-03-15T00:05:03Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DWp+nDyPN4uwSAQdAkYJOrpneMjMC3FMqmSe97iflls91TpWKJNl7JvMLxgQw
            AxFLci9bMblBuq6bieNxtGXYCzSWU0hy5Ao8e8AYSDQf+73Y00r5BvYNO0reEP9K
            0l4B2x7lYfyLqaD8qhXC95H6ogM0z/2otVBdQfEYf6Bzi1XUyePhiNa/bCiMkiFd
            tIibA8GTg3MCMjiFKhNyBHbCg0vvx/diMfVb7fOmduNaeua48LNba5cX6sg+1EBo
            =p93v
            -----END PGP MESSAGE-----
          fp: 2EE325D71601671696EBF687E45953D34C8829ED
    unencrypted_suffix: _unencrypted
    version: 3.11.0
