seed:
    k3s-token: ENC[AES256_GCM,data:P3BIBB7kRzyZMgtWRH26i4gqQTBrQdRRkkG+N9w2NzMdRQ+tdBT//vsgWzFld0QaPHwd10jk44igVY64m8D6QnFOMOGkYqrrYB1EnANlHihb4dihbTUpJCyJZ+kfeFZZHLXq/8qLJYYlZ+RgwW95DNp/4bgJF5Wj9xK55uzHv6N/UKfw9eFoGxyeUxY=,iv:JcB6ep5K/crtbbES8TINfOsumCOuWq4TU0anvsQ571Q=,tag:stzxNlH0iGzxHOy4Nvpkog==,type:str]
sops:
    age:
        - recipient: age16kvu4zv76gnuenewe3eaphx5uq5xd4hcw9qpf6x7ltgtlsm9kp2s05uvwy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBseloyNlREUWxUR09IcnBS
            ZDZxUHIwQVhMUkI4a2VtRVVINllFVEtJaUhFCk91elBoeFZudFg1NnhTc1lDOGh1
            alNkdEY3ejNWd2ZFYXZLcVNRY3ZFcVUKLS0tIGRtZC9wYlZ2UTJGUHZ5Z1NFWi9l
            V2JGM2hPZnY1UUZUcWJnUzBSYmZOT1UK0lHfbRgutgXATDZyPrqx2A/gn59H3Lj1
            EI44DmpKltks1mU/zpSmuyofM3bcfiNvQMAhy++IkRD6YS34r7bajg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-13T05:23:11Z"
    mac: ENC[AES256_GCM,data:sBj8o6TTpfxRdDBtrmw2E76z2EaXkwQbwZRMkx8VjN0ZWi0L7n0iaGz8M1ANOLPv5W7JvJ3IUUBh8cBWR5EBzHKw5TS5yOasqcqpe+39N3DSSgmuISYDmY2Y/Ux+SzSz/NO6Xz82wz4zW/5IuGIzLumIcyI1cDQq2uS1Asrw1KI=,iv:gfaAKfGtI7CyWLgywBVCHpF7Y2xGg12xC+aNhngb/DY=,tag:5nK9qRXm1K//TZURJmunwg==,type:str]
    pgp:
        - created_at: "2026-03-13T05:23:11Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DWp+nDyPN4uwSAQdAKd4ngr4pXYf1YO9isvxhckOmbFMGBnadwUbbdpis/h4w
            qk8WHoXZWB/0V60u7Q4qFMlwtgMXRCnjiOFDotTsLj+blt0RmXqDvgk7Xjfk8uu8
            0l4Bl5twSqXGFw+4JfhyOK5L8WkNmkKLXFD5kuAGb86RIftOzhwLQgl0Ag46TYod
            xAqC55VW8Ndve8+Gb64DxH+a0xCJ+J6WL4bCyk+eUj0fVZm9Tp45RNeR6ecofWbC
            =kgd/
            -----END PGP MESSAGE-----
          fp: 2EE325D71601671696EBF687E45953D34C8829ED
    unencrypted_suffix: _unencrypted
    version: 3.11.0
