seed:
    cache-signing-key: ENC[AES256_GCM,data:xRwLPwYdXtoq3fnToXCmZmACW6svN7mrz3j2Qhnr65geUjYVJD2ndn61X5QCPosCh13CFkJRgfMuE2Xkk+XNrf4JFUcLk6veqWhwJ7ZWIdyLLqWh9ZFh+1z32QI3+9b2M+bySeQ=,iv:qex9mbTCrp2jMmzLyrvkV/rNWKqsugNS8Zc5RGjr2zs=,tag:/+erbCgtmVW7mkE2IDhi3w==,type:str]
    s3-access-key: ENC[AES256_GCM,data:BXd3m0YGK+ES0rlMxH4RbgEYhaI=,iv:KEQrIzgEgiYiN3jLi46RDuCeNKHaQGnNcy9EsmeE6L4=,tag:BSK/3hXc8rs0386wvDQ1Ig==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:8wxGwyHd2Ck2Q8zO0lh6nofC6H1soT/sLTln/907gZnhAdx9SLGnNQ==,iv:nEQYBppylQOyC6Mi5XIaFgjsAZAag2E6nKWbdrVIuyg=,tag:N6HVcTXD+gIGpMKZZAoxmw==,type:str]
    controller:
        gh-webhook-secret: ENC[AES256_GCM,data:TkhC4+SHTHcqxiGvp+twcpWoS3S4KZ56MiOozkJF/o5hDzr6meIlxqYo5oU=,iv:M9AHvwY9eZNzXgYKJLnAJU0gKzomvjNfbELeaXwJ6oE=,tag:B8ihAOka8lKxzjXEbWI7FQ==,type:str]
        pdns-api-key: ENC[AES256_GCM,data:1Iz276hNppzE7t/Si8domOBH2RH8JU7D0IM4bu1isUNPkZTS0GTNMRzIqFc4w14B4v0CVUYP6LcwQ5wQXz8fsg==,iv:mxdfPHzh6cE1KNkpYOYAH4SfPjI5JhMPcAn+7j9Gbuo=,tag:A9osz+ke7md8QiSsfGbl3g==,type:str]
ceph:
    mon-key: ENC[AES256_GCM,data:8QNLuDieXVboV2qw/QR9790ipMhzBVZkCsUVX/3jrKr+rhQ5uZ4s9A==,iv:cNPJuGd3h5IFQIi7LOTULapyH3vE/RWnKZIw7NwCKU4=,tag:TUmtzJxNonEmJwAJMme4CQ==,type:str]
    admin-key: ENC[AES256_GCM,data:vdnRZjlrAPd+jPMquATqQxLwMEclqVRO7p1yvkoo+FpdrDQ3Yst3EA==,iv:MNCpjvp79NBBClr9XgAHRqPNY0hTs6f+DgNbtrmJwbs=,tag:FzxLh+QHpt2rWWla2P0iMQ==,type:str]
    csi-k8s-key: ENC[AES256_GCM,data:vsXe40Or3F9amQVdHCym8b7P5xXqZ8KeqFvZyxesXdZjw9DAndqWXA==,iv:H0JeolbzXA9gB1RzElJprDpZILStjwgbfm1mF1zJ7Yc=,tag:7Kd2inVu5YrBdOzChSXhrA==,type:str]
sops:
    age:
        - recipient: age1uzdjpvu5ftf5um2veavl85r2hht89afk2l3sajxj3ehc7wa9ya5s9fqlrh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuRUFjb2QvalNBbG9qYjRm
            T0VUNmtXejhtajJxVmlWYmNxUi9YZms3eFRvClB6YzBya1UwLzJuR1N3cXduNHZO
            a0dzZDA1Wi91bFVkcGRYZlRGdmxISWMKLS0tIEFZRzBiOWo0amdZS3p6Q2N3MzJZ
            cFFFbWtrdDFNaTNPS0F0eXlIM0xGTlkKH3X5+MblM8SmR9qLv7FwGaj1h0w/bFmh
            5BvmlprmKyM2qxuZZB54EANxayVl5+UglHkTcKskW6VAD6Df26PKWw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1nachhe6fxyqj8wzzypxg7lh8utg2pdn7mrg5jty77keunemcau8q0pxnhx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2NkxkR0VVZTFNZU9TK1FU
            Z0paWWt1RWpibkdpRm1BVVJNU3FtelFCQVFvCncxSUlXZHFnSVIxMVNDTzUveVFu
            QjBHMTFocTdKV1pQa2J6MzNPUEhmMDAKLS0tIDdlUDlsVzVGKzFzZWlhZjZBSW5y
            ZVhhNmJpSHFkYkgzWlU5ZDc1RjdQZzgKSH2THOIFE38zO8xw2knaQMVND/ezCcxI
            +Bzz97qUfbFZxwZBvkAm8BDXBPe7dcEHA2//e3dF5sUMXK/mZELt7g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ggj5uuyt5x0vrt4fmcu8lnt0f3qzqkxjm8qpqrplckvpz2s2ugdquuzn78
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5YjNpRXk4cFlBL1JyWjdk
            bFdtZ1M4L3lUZjYyUVI4OVVrMjZkNkxia1YwCnhvM2ViNjNqdmxnSzNkUE1wUFYw
            TzRicTFtNXdXZU9KWmU2eWtjNU9KM00KLS0tIHZXM3ZsVFZxajI4b3dpeVJqWU9U
            bUYwcWxsanRzOElTWEMycE9wVWVIUWMKF+gWloxooNqDruCQmI63ER+rMhRC3++G
            ej6gtDHniSjyx5zXqsIiK5hmDdMRcSRglsunWtKLLJ5n0EWOxcGXXw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1uzcjxhj5jnu0r5h0q8cqf7rj4tzdcp5zs6xk4rv0257n32pfxvysj7lvm3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3Ym5KRjBuQUFxWGJNNndY
            SWNIcXYrYUpVMHhTcjVrd0hCa0hKVHdoZFJzClRTZFZHVzVLMko3NjlNNjg5Rk1O
            LzZ6aWp6SmcxTGFsalp3cy91WU9aRXcKLS0tIGNBMUt2bzQwYVBrUEF3S2laekNi
            c3FIcXcvZzBjbThpV012cU45RWNnaGcKGID8iBFuM2vIGye5QPLVLzj51rhfPZ+h
            hnk2ViuThYAj9VR8lnLYaN1PcYH8Q0nEukmLMPMz0mlw78UXG46VOQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1s3qkxjd29dd6mvttvruf6mpzue2lun3qmyfnycgk8t6c7ftz7vpqa87flk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjSjFKcTdYN3kxdlZZc2R0
            NzNzbDdYVkIvWUtreVRBS0JuaFBtcW1BZ0Y4CmxXNHprT1N2aUxOdXpHR3pSb1Qz
            ckRTVVNoSGhCeHd0bGxFd3dESjBGalUKLS0tIGFxTFRoOHJndHN5UWc0NnRDT0x5
            RGVVWHYrMTlmaEhxYVlKTXNaYkdHZ2cKVBo1NG18/Ffkwq6zntbgsHh2N6qUXfIY
            esbM3ijfpDo5ESv/UoFu6enxH71SnUbLGaBlIQaI5ak7LEUcc3Nn9Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1kazl566j80pl3eshzqv9c0wyq843g8ep7vt27su03e4jg6eg64gqv6qnwl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvQVFhTGx5UFRheDA1dHZL
            bzRkNTlhQjRPN09UUWh1WXExZTI1QitBd0dFCmlQbTFrcWZjZUt1NkZRQ0YrK0hv
            bkZkVHFLbXFsc2tsazJ5L2cvd1NvYkUKLS0tIExNVDBOR3IyamFKcHhZTnFlQTVF
            TEdMN0pGc3JkUlBMellySDVBbWJlZVUKhVDijt/93TFM0Du0ncR61lFwLBHObiUU
            A0tc0LjfuwwUMe0k1e7rII6YNg2txhRGVKxwsHR7A6XiKXLxOm//Cw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ujjm7feyd3p2e0qtfa6zr2rzf593yd2z0xjn0ytvd8jcje68nansxy4zuu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOU1JjQktTNysrTlZYaTZX
            QjhKY1hkVjM2VkErTHo1RnJVSmt1R1FkNUdjCmljQUtZbGU5QUhxOEtkTzFSTUlo
            NkhCZTVhTXc2dkhUMUdlcFI3UndvOU0KLS0tIDYwUDNDU1FnSjBiMkNJeHRwRkFG
            RWh4TGd2WGJteFl5MDJZdkwzY1FNa2sKjLe4LvD78s5r0e/mwHr2HRV3bjmSiv1t
            O73ofbURn8l7FGjehyNq5SXtaTkMeHZMir68jcW4IMwPW+wTQduLoQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T17:39:41Z"
    mac: ENC[AES256_GCM,data:Ic0e3jrLvWDtsPY9slQTgsMbHLuX2EA7yt0F9aTVmjD/0728VrpvBZd3A3T7nvPFahn5fN9f7HGPj+NOZNFD1pzBvitXJTtZ8CYrne8EjAL5wXl8Xdg44XzJW/whvse3gJdB1Y+8RYTJR3hpIvqaGrMr0uqUhhSLNw0qUyp9/Ts=,iv:IcWmshnvXNG/TQrtFg9o4sFvGHvieZPP4OQ/qmHj5Ps=,tag:OTl3r+8s58PUKzk5/JMufQ==,type:str]
    pgp:
        - created_at: "2026-03-15T01:17:48Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DWp+nDyPN4uwSAQdAJKbVbs8hTM11G8v+MYAsaYyzMpnOUs090RggFm7GBT8w
            9RxWgCbx18ObgNp1/w8f9mP/frH9mC8uMqifBqthBTpSqUk6WGjSLRumSs3ClQUS
            0l4BMh69wg7b0Em4WIdEMZoFIet7GAcAPS8NlFxdMJrmrJ5ro2Rf7Ak9F5LcF6zO
            vEuxvNQPEgIwfrRUTeQfJ32C9mt4TNQFyfc5cwG/e4NTGITVuMLilXjWBQQmVqSQ
            =GBXR
            -----END PGP MESSAGE-----
          fp: 2EE325D71601671696EBF687E45953D34C8829ED
    unencrypted_suffix: _unencrypted
    version: 3.11.0
