keys:
  - &admin_josh 2EE325D71601671696EBF687E45953D34C8829ED
  - &ada_age age1ujjm7feyd3p2e0qtfa6zr2rzf593yd2z0xjn0ytvd8jcje68nansxy4zuu
  - &seed_atl1_1_age age1neey2tjnrka26dndtwp400y5auud86v92f09srdr3xun80exv5jqcnlq6t
  - &seed_atl1_2_age age16kvu4zv76gnuenewe3eaphx5uq5xd4hcw9qpf6x7ltgtlsm9kp2s05uvwy
  - &seed_atl1_3_age age1x6fmwskwxvacf9nnsafexvpgfdl9ugj9xf9fvpvfng3rkukc3yxskddr3p
  - &seed_tang_1_age age1s3qkxjd29dd6mvttvruf6mpzue2lun3qmyfnycgk8t6c7ftz7vpqa87flk
  - &stake_age age1uzdjpvu5ftf5um2veavl85r2hht89afk2l3sajxj3ehc7wa9ya5s9fqlrh
  - &puncher_atl1_1_age age1ae83xwy93c4u9nrzu8gtdyr9ks9c3zu44p7dmc78penpenaysgnqq5xqgx

creation_rules:
  - path_regex: secrets/stake\.yaml$
    key_groups:
      - pgp:
          - *admin_josh
        age:
          - *stake_age

  - path_regex: secrets/seed-atl1-1\.yaml$
    key_groups:
      - pgp:
          - *admin_josh
        age:
          - *seed_atl1_1_age

  - path_regex: secrets/seed-atl1-2\.yaml$
    key_groups:
      - pgp:
          - *admin_josh
        age:
          - *seed_atl1_2_age

  - path_regex: secrets/seed-atl1-3\.yaml$
    key_groups:
      - pgp:
          - *admin_josh
        age:
          - *seed_atl1_3_age

  - path_regex: secrets/seed-tang-1\.yaml$
    key_groups:
      - pgp:
          - *admin_josh
        age:
          - *seed_tang_1_age

  - path_regex: secrets/puncher-atl1-1\.yaml$
    key_groups:
      - pgp:
          - *admin_josh
        age:
          - *puncher_atl1_1_age

  - path_regex: secrets/seed-system-atl1\.yaml$
    key_groups:
      - pgp:
          - *admin_josh
        age:
          - *stake_age
          - *seed_atl1_1_age
          - *seed_atl1_2_age
          - *seed_atl1_3_age
          - *seed_tang_1_age
          - *puncher_atl1_1_age
          - *ada_age

  - path_regex: secrets/luks-recovery\.yaml$
    key_groups:
      - pgp:
          - *admin_josh
        age:
          - *ada_age

  # Fallback
  - path_regex: secrets/.*\.yaml$
    key_groups:
      - pgp:
          - *admin_josh
        age:
          - *ada_age
